# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts && npm install @modelcontextprotocol/sdk && npm install node-notifier zod && npm install typescript @types/node @types/node-notifier --save-dev --ignore-scripts

# Copy source
COPY . .

# Build project
RUN npm run build

# Expose any port if needed (not needed for stdio)

# Set entrypoint
ENTRYPOINT ["node", "dist/index.js"]
